version: '3.8'

services:
  data-collector:
    build: ./services/data-collector
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BATCH_SIZE=100
      - BATCH_INTERVAL=5
    depends_on:
      - mongodb
      - mosquitto
      - redis

  data-provider:
    build: ./services/data-provider
    ports:
      - "8001:8001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MAX_CONNECTIONS=1000
      - WORKER_COUNT=4
    depends_on:
      - mongodb
      - redis

  api-key-manager:
    build: ./services/api-key-manager
    ports:
      - "8002:8002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - API_KEY_SECRET=${API_KEY_SECRET}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 2gb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - URL=/api-docs/openapi.json
    volumes:
      - ./api-docs:/usr/share/nginx/html/api-docs

volumes:
  mongodb_data:
  redis_data: 